// This file is generated by Slice Machine. Update with care!

import Publications from './Publications';
import PublicationsPosts from './PublicationsPosts';

export {
	Publications,
	PublicationsPosts,
};

export const components = {
	publications: Publications,
	publications_posts: PublicationsPosts,
};
